name: tsrct_cli
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.6 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.2
  googleapis: ^11.2.0
  googleapis_auth: ^1.4.1
  pointycastle: ^3.7.3
  tsrct_dart_lib:
    git: git@github.com:tsrct/tsrct-dart-lib.git

